import type { Metadata } from 'next';
import { Header, SectionIndex } from '../site';
import ArrowIcon from '../arrow-icon';
import Portfolio from './portfolio';
import { booking, instagram, reviewsUrl, giftUrl, piercings, categories, faq } from './data';
export const metadata: Metadata = {title:'Black Lotus — piercing promyšlený do detailu | V2', description:'Od výběru umístění a šperku až po hojení. Black Lotus, piercingové studio v Praze.',robots:{index:false,follow:true}};
function CTA({href,children,light=false}:{href:string;children:React.ReactNode;light?:boolean}) {return <a href={href} className={`button ${light?'button-light':'button-dark'}`}>{children}<ArrowIcon /></a>}
function Heading({n,label,children}:{n:string;label:string;children:React.ReactNode}) {return <><SectionIndex index={n} label={label}/><h2 className="v2-heading">{children}</h2></>}
const process = [['IDEA','Probereme vaši představu.'],['ANATOMY','Zkontrolujeme vhodnost umístění.'],['JEWELLERY','Vybereme správný šperk.'],['PLACEMENT','Přesně označíme pozici.'],['PIERCING','Piercing provedeme sterilní jednorázovou jehlou.'],['AFTERCARE','Vysvětlíme péči a další postup.']];
const safety = [['PREPARATION','Příprava','Oddělená pracovní plocha. Připravený materiál a ochranné pomůcky.'],['DISINFECTION','Dezinfekce','Ošetření ploch a příprava místa aplikace.'],['ULTRASONIC CLEANING','Ultrazvuk','Předčištění a ultrazvukové čištění opakovaně použitelných nástrojů.'],['AUTOCLAVE','Autokláv','Po oplachu, sušení a zabalení následuje parní sterilizace a kontrola cyklu.'],['STERILE STORAGE','Sterilní skladování','Kontrola obalů a uložení sterilního materiálu do použití.']];
export default function HomeV2(){return <main className="v2">
 <Header lang="cs" variant="v2" />
 <section className="hero v2-hero">
  <img src="/assets/hero-main.webp" alt="Detail ucha s titanovým šperkem" className="hero-image" />
  <div className="hero-shade"/><div className="hero-topline"><span>PIERCING STUDIO / PRAHA</span><span>PRAGUE / CZ</span></div>
  <div className="hero-copy"><p className="eyebrow light">BLACK LOTUS® / OD ROKU 2015</p><h1>Piercing<br/>promyšlený<br/>do detailu.</h1><div className="hero-action-row"><p>Individuální výběr umístění a šperku. Profesionální aplikace. Péče během celého hojení.</p><CTA href={booking} light>OBJEDNAT TERMÍN</CTA></div><a className="text-link" href="#piercing-index">PROHLÉDNOUT PIERCINGY <ArrowIcon/></a></div>
 </section>
 <div className="v2-spec-strip frame"><span>ASTM F-136 TITANIUM</span><span>STERILE SINGLE-USE NEEDLES</span><span>PRAGUE / CZ</span></div>
 <section id="piercing-index" className="frame section-space"><Heading n="02" label="PIERCING INDEX">Co chcete píchnout?</Heading>
  <div className="v2-index">{categories.map((category,i)=><article key={category}><span className="v2-label">0{i+1} / {category}</span><div className="v2-index-names">{piercings.filter(p=>p.category===category).map(p=><a key={p.slug} href={`/v2/piercing/${p.slug}`}>{p.name}<ArrowIcon/></a>)}</div><div className="v2-index-meta"><a href={`/v2/piercing/${piercings.find(p=>p.category===category)!.slug}#price`}>CENA</a><a href={`/v2/piercing/${piercings.find(p=>p.category===category)!.slug}#healing`}>HOJENÍ</a><a href={`/v2/piercing/${piercings.find(p=>p.category===category)!.slug}`}>DETAIL <ArrowIcon/></a></div></article>)}</div>
 </section>
 <section id="anatomy" className="v2-cold section-space"><div className="frame"><Heading n="03" label="ANATOMY / CONSULTATION">Ne každý piercing<br/>patří na každou<br/>anatomii.</Heading><div className="v2-editorial"><p className="v2-statement">A to je v pořádku.</p><div><p>Před aplikací vždy zhodnotíme konkrétní anatomii. Pokud zvolený piercing není vhodný, vysvětlíme proč a navrhneme jinou možnost.</p><div className="v2-tags"><span>ANATOMY</span><span>PLACEMENT</span><span>JEWELLERY</span><span>LIFESTYLE</span></div><p className="v2-lead">Máte inspiraci? Přineste ji.<br/>Nemáte? Vymyslíme ji společně.</p><CTA href={booking}>KONZULTACE</CTA></div></div></div></section>
 <section id="process" className="frame section-space"><Heading n="04" label="PROCEDURE / 06 STEPS">Jak návštěva probíhá</Heading><div className="v2-process">{process.map(([label,text],i)=><article key={label}><span className="v2-label">0{i+1} / {label}</span><p>{text}</p></article>)}</div></section>
 <section id="piercers" className="frame section-space v2-rule"><Heading n="05" label="PEOPLE BEHIND BLACK LOTUS">Dva pierceři.<br/>Jeden standard práce.</Heading><div className="v2-piercers">{[['alex','A','Alex','Piercer od roku 2015. Klidné vysvětlení, přesné umístění a respekt k vašemu tělu.','ZAMĚŘENÍ / ANATOMIE & UMÍSTĚNÍ'],['maky','M','Maky','Prostor pro otázky, srozumitelné vedení návštěvou a individuální výběr šperku.','PŘÍSTUP / KONZULTACE & PÉČE']].map(([id,letter,name,copy,focus])=><article id={id} key={id}><div className="portrait monogram" aria-hidden="true">{letter}</div><div className="v2-piercer-copy"><span className="v2-label">PIERCER / {id==='alex'?'01':'02'}</span><h3>{name}</h3><p>{copy}</p><span className="v2-label">{focus}</span><a href={instagram} className="text-link">PORTFOLIO STUDIA <ArrowIcon/></a></div></article>)}</div><p className="v2-lead v2-shared">Umístění, šperk i následnou péči řešíme individuálně — podle anatomie, životního stylu a konkrétního piercingu.</p></section>
 <section id="jewellery" className="material section-space"><div className="frame material-grid"><div><Heading n="06" label="JEWELLERY / FIT MATTERS">Šperk není jen detail.<br/>Je součást piercingu.</Heading><p>U čerstvého piercingu záleží na materiálu, délce, tvaru i konstrukci šperku. Proto vybíráme každý šperk podle konkrétního piercingu a anatomie.</p><dl className="v2-specs"><div><dt>MATERIAL</dt><dd>ASTM F-136 TITANIUM</dd></div><div><dt>SIZE</dt><dd>INDIVIDUAL FIT</dd></div><div><dt>FORM</dt><dd>ACCORDING TO ANATOMY</dd></div></dl><a href="https://lotusjewelry.cz/" className="text-link">PROHLÉDNOUT ŠPERKY <ArrowIcon/></a></div><div className="material-object"><img src="/assets/titanium.webp" alt="Detail titanového šperku" loading="lazy"/><span className="object-note left">Ti / ASTM F-136</span></div></div></section>
 <section id="safety" className="frame section-space"><Heading n="07" label="SAFETY / STERILISATION">Bezpečnost není slogan.<br/>Je to proces.</Heading><div className="v2-safety">{safety.map(([label,title,copy],i)=><article key={label}><span className="v2-label">0{i+1} / {label}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><p className="v2-note">Jehly jsou sterilní a jednorázové. Čištění a sterilizace nástrojů jsou samostatné kroky.</p><a className="text-link" href="/studio#sterilisation">VÍCE O STERILIZACI <ArrowIcon/></a></section>
 <section id="portfolio" className="frame section-space v2-rule"><Heading n="08" label="PORTFOLIO">REAL WORK /<br/>REAL ANATOMY</Heading><Portfolio/><a className="text-link" href={instagram}>VIEW ALL WORK <ArrowIcon/></a></section>
 <section id="prices" className="v2-cold section-space"><div className="frame"><Heading n="09" label="PRICE / TRANSPARENT">Kolik piercing stojí?</Heading><div className="v2-prices">{piercings.filter(p=>['helix','conch','nostril','septum'].includes(p.slug)).map(p=><a key={p.slug} href={`/v2/piercing/${p.slug}#price`}><span>{p.name}</span><i/><strong>od {p.price.toLocaleString('cs-CZ')} Kč</strong><ArrowIcon/></a>)}</div><p>Základní šperk z titanu ASTM F-136 je u vybraných piercingů součástí ceny.</p><a className="text-link" href="/piercing">CELÝ CENÍK <ArrowIcon/></a></div></section>
 <section id="healing" className="technical section-space"><div className="frame"><Heading n="10" label="AFTERCARE / CONTINUITY">Piercingem to nekončí.</Heading><div className="v2-healing">{[['APPLICATION','Aplikace'],['HEALING','Hojení'],['CHECK-UP','Kontrola'],['DOWNSIZE','Zkrácení šperku']].map(([tag,title],i)=><div key={tag}><span className="v2-label">0{i+1} / {tag}</span><h3>{title}</h3></div>)}</div><div className="v2-editorial"><p className="v2-lead">Po aplikaci začíná nejdelší část procesu.</p><div><p>Pomůžeme vám s péčí, kontrolou i případným zkrácením šperku.</p><a href="/care#healing" className="text-link">PRŮVODCE HOJENÍM <ArrowIcon/></a></div></div></div></section>
 <section id="check-up" className="frame section-space"><Heading n="11" label="CHECK-UP / WE ARE HERE">Je to v pořádku?</Heading><div className="v2-check"><article><span className="v2-label">01 / BĚŽNÉ</span><p>Zejména na začátku se mohou objevit:</p><ul>{['mírný otok','citlivost','svědění','krustičky','čirá nebo bělavá sekrece'].map(t=><li key={t}>{t}</li>)}</ul></article><article><span className="v2-label">02 / OZVĚTE SE NÁM</span><p>Na kontrolu nemusíte čekat, pokud řešíte:</p><ul>{['rostoucí bolest','silný otok','zařezávající se šperk','změna polohy','problém se šperkem','nejistota'].map(t=><li key={t}>{t}</li>)}</ul></article></div><p className="v2-note">Při horečce, šířícím se zarudnutí nebo podezření na infekci vyhledejte lékaře. Kontrola ve studiu nenahrazuje lékařské vyšetření.</p><CTA href={booking}>KONTROLA PIERCINGU</CTA></section>
 <section id="gift" className="v2-gift technical section-space"><div className="frame"><Heading n="12" label="GIFT / BLACK LOTUS">Darujte piercing.<br/>Výběr nechte na nich.</Heading><div className="v2-editorial"><p className="v2-lead">Dárkový poukaz lze využít na piercing, šperk nebo další služby studia.</p><div><div className="v2-gift-formats"><div><span>DIGITAL</span><p>e-mailem po zaplacení</p></div><div><span>PRINT</span><p>vyzvednutí ve studiu</p></div></div><CTA href={giftUrl} light>KOUPIT DÁRKOVÝ POUKAZ</CTA></div></div></div></section>
 <section id="reviews" className="frame section-space"><Heading n="13" label="CLIENT NOTES / TRUST">Co říkají naši klienti</Heading><div className="v2-reviews">{[['01 / KLID','Umí i dobře uklidnit nervozitu.','Leila Ahmadzai'],['02 / NÁSLEDNÁ PÉČE','Aftercare service taky na jedničku.','Barbara Volfová'],['03 / PODPORA','Pomoc před a po.','Vika Nov']].map(([tag,quote,name])=><figure key={name}><span className="v2-label">{tag}</span><blockquote>„{quote}“</blockquote><figcaption>{name}<a href="https://lotuspiercing.cz/">Výňatek z recenze na webu studia <ArrowIcon/></a></figcaption></figure>)}</div><a href={reviewsUrl} className="text-link">VŠECHNY RECENZE <ArrowIcon/></a></section>
 <section id="faq" className="frame section-space v2-rule"><Heading n="14" label="BEFORE YOU BOOK">FAQ</Heading><div className="v2-faq">{faq.map(([question,answer],i)=><details key={question}><summary><span>0{i+1}</span><h3>{question}</h3><b aria-hidden="true">+</b></summary><p>{answer}</p></details>)}</div><a href="/v2/faq" className="text-link">VŠECHNY OTÁZKY <ArrowIcon/></a></section>
 <section className="frame section-space v2-final"><SectionIndex index="15" label="YOUR NEXT PIERCING"/><h2>Máte představu?<br/><span>Nemáte?<br/>To nevadí.</span></h2><div className="v2-final-actions"><p>Společně vybereme piercing, umístění i šperk.</p><div><CTA href={booking}>OBJEDNAT TERMÍN</CTA><a href={booking} className="text-link">KONZULTACE <ArrowIcon/></a></div></div></section>
 <footer id="contact" className="footer frame v2-footer"><div className="footer-brand"><span className="brand-monogram brand-monogram-footer" role="img" aria-label="Black Lotus"/><h2>BLACK LOTUS</h2><p>PIERCING STUDIO / PRAGUE</p></div><div><span>ADRESA / ADDRESS</span><a href="https://maps.google.com/?q=Petrohradská+388/22+Praha">Petrohradská 388/22<br/>Praha 10 — Vršovice</a><span>OTEVÍRACÍ DOBA / OPENING HOURS</span><a href={booking}>Dostupnost podle rezervačního kalendáře</a></div><div><span>KONTAKT / CONTACT</span><a href="tel:+420777547240">+420 777 547 240</a><a href="mailto:piercingprague@gmail.com">piercingprague@gmail.com</a><a href={instagram}>INSTAGRAM <ArrowIcon/></a><a href={booking}>BOOKING <ArrowIcon/></a></div><div><span>NAVIGACE</span>{[['PIERCING','#piercing-index'],['STUDIO','#safety'],['ALEX','#alex'],['MAKY','#maky'],['CARE','#healing'],['JEWELLERY','#jewellery'],['GIFT CARD','#gift'],['CONTACT','#contact'],['BLOG','/journal']].map(([label,href])=><a key={label} href={href}>{label}</a>)}</div><p className="copyright">© BLACK LOTUS PIERCING STUDIO / 2015—2026</p></footer>
 </main>}
